services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontendContainer
    ports:
      - "8000:80"
    networks:
      - examenInternal
    depends_on:
      - backend

  # Backend
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backendContainer
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
    networks:
      - examenInternal
    depends_on:
      - mysql

  # Base de Datos
  mysql:
    build:
        dockerfile: database.Dockerfile
    container_name: databaseContainer
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - databaseVolume:/var/lib/mysql
    networks:
      - examenInternal

networks:
  examenInternal:
    driver: bridge

volumes:
  databaseVolume:
